In [12]:
import numpy as np

## $Statistics$ $+$ $NumPy$
---

### Exercises:
* Generate a 1D NumPy array with the values [7, 9, 65, 33, 85, 99]
* Generate a matrix (2D NumPy array) of the values:

\begin{align}
    \mathbf{A} = 
    \begin{pmatrix}
        1 & 2 & 4 \\ 
        2 & 3 & 0 \\ 
        0 & 5 & 1 
    \end{pmatrix}
\end{align}


* Change the dimensions of this array to another permitted shape
* Run the code below and attempt to reshape the data array to the correct format

```
c1 = np.randint(0, 110, 50)
c2 = np.random.rand(50)
c3 = np.random.choice(['french', 'english'], 50)
data = np.column_stack((c1, c2, c3)).flatten()
```

In [19]:
oneDimensional = np.array([[7, 9, 65, 33, 85, 99]])
print(oneDimensional, " is ", oneDimensional.shape)

[[ 7  9 65 33 85 99]]  is  (1, 6)


In [27]:
twoDimensional = np.array([[1, 2, 4, 2, 3, 0, 0, 5, 1]]).reshape(1, 9)
print(twoDimensional)

[[1 2 4 2 3 0 0 5 1]]


In [28]:
reshaped = twoDimensional.reshape(3, 3)
print(reshaped)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [41]:
c1 = np.random.randint(0, 110, 50)
c2 = np.random.rand(50)
c3 = np.random.choice(['french', 'english'], 50)
data = np.column_stack((c1, c2, c3)).flatten()

reshapedData = data.reshape(50, 3)
print(reshapedData[:5])

[['56' '0.9640075021915289' 'english']
 ['7' '0.4440231135290146' 'french']
 ['7' '0.3044065376998273' 'english']
 ['48' '0.7198192221712646' 'english']
 ['74' '0.48939179433983226' 'french']]
